### ISSUE TITLE
SkinnedMeshRenderer?

### ISSUE THREAD

**Issue by dustinlacewell** [dgreenheck/OpenFracture#14]
Does this work with SkinnedMeshRenderers? Anyway I could?

**Comment by dgreenheck** [comment]
It has been some time since I worked on this, but I believe the answer is no. Could it? Yes, but it would likely require significant work. From a quick read up, a skinned mesh takes the base mesh data and transform it in realtime using the underlying skeleton.

I remember seeing some fracturing/slicing solutions that handled skinned meshes but I don't remember what they were, sorry.
