### ISSUE TITLE
Regarding the self-intersecting mesh limitation

### ISSUE THREAD

**Issue by Modeuser** [dgreenheck/OpenFracture#2]
Would anyone happen to know what kind of error message unity would display if I tried to slice a mesh with a self-intersecting/non-closed mesh? Just wanted to check if an issue I've been having is due to this limitation.

**Comment by dgreenheck** [comment]
There won’t be any error. The triangulation algorithm which fills in the new faces will simply produce unexpected results. Can you post a screenshot of the issue? It’s also worth checking over your model in a 3D modeling app like Blender to verify there isn’t any problematic geometry. Unfortunately, I don’t know of a way to automatically detect if a mesh has self-intersecting or open geometry.

**Comment by TheScabbage** [comment]
The 3D printing addon for blender is good for checking these kinds of mesh properties. It can automatically select degenerate or overlapping faces, and check whether the mesh is manifold.

To detect an open mesh: 
- merge all duplicate verts
- ensure every edge is used by exactly 2 faces

I'm not sure of a performant way to find self intersecting meshes though.

**Comment by dgreenheck** [comment]
@Modeuser FYI, here is a paper for triangulation of self-intersecting polygons: [FIST: Fast Industrial Strength Triangulation of Polygons](http://citeseerx.ist.psu.edu/viewdoc/download?doi=10.1.1.49.3013&rep=rep1&type=pdf). It also appears to be faster than Sloan's algorithm (the algorithm used in OpenFracture) for most scenarios.

I initially used this paper but had issues extending it to handle polygons with holes. It's a much more complex algorithm with multiple phases and recovery modes. I ended up pivoting and switching to Sloan's algorithm I did because it does not need to handle special edge cases which I felt was a better approach to keep things more robust. I figured most meshes are closed and can easily be modified to avoid self-intersecting geometry.

**Comment by Modeuser** [comment]
@dgreenheck Here's the error message I'm getting:

![fragment error with obj file](https://user-images.githubusercontent.com/52872086/150885393-5bfbdbc4-3f30-4981-8278-da7c84ab62a5.PNG)

Some context:

I adapted your script for the new input system and various XR interactions, so far it's working great with most of my mesh files (.fbx).

But when I tried to slice a recently added .obj file, nothing happens and this error message gets reported in the Unity debugger.

**Comment by dgreenheck** [comment]
@Modeuser  Set a breakpoint on that line. Your mesh is likely missing UVs.
